
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.openhab.binding.atsadvanced.webservices.client;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-23T16:43:57.530+02:00
 * Generated source version: 3.0.0-milestone2
 *
 */

@javax.jws.WebService(serviceName = "SyncReply", portName = "BasicHttpBinding_ISyncReply", targetNamespace = "ATSAdvanced.DTO", wsdlLocation = "http://127.0.0.1:1337/soap11", endpointInterface = "org.openhab.binding.atsadvanced.ISyncReply")

public class BasicHttpBinding_ISyncReplyImpl implements ISyncReply {

    private static final Logger LOG = Logger.getLogger(BasicHttpBinding_ISyncReplyImpl.class.getName());

    /*
     * (non-Javadoc)
     * 
     * @see
     * org.openhab.binding.atsadvanced.ISyncReply#programSendMessage(org.openhab.binding.atsadvanced.ProgramSendMessage
     * par )*
     */
    @Override
    public org.openhab.binding.atsadvanced.webservices.client.ProgramSendMessageResponse programSendMessage(
            ProgramSendMessage par) {
        LOG.info("Executing operation programSendMessage");
        System.out.println(par);
        try {
            org.openhab.binding.atsadvanced.webservices.client.ProgramSendMessageResponse _return = new org.openhab.binding.atsadvanced.webservices.client.ProgramSendMessageResponse();
            org.openhab.binding.atsadvanced.webservices.datacontract.ArrayOfProgramProperty _returnProperties = new org.openhab.binding.atsadvanced.webservices.datacontract.ArrayOfProgramProperty();
            java.util.List<org.openhab.binding.atsadvanced.webservices.datacontract.ProgramProperty> _returnPropertiesProgramProperty = new java.util.ArrayList<org.openhab.binding.atsadvanced.webservices.datacontract.ProgramProperty>();
            org.openhab.binding.atsadvanced.webservices.datacontract.ProgramProperty _returnPropertiesProgramPropertyVal1 = new org.openhab.binding.atsadvanced.webservices.datacontract.ProgramProperty();
            _returnPropertiesProgramPropertyVal1.setId("Id-1877409047");
            _returnPropertiesProgramPropertyVal1.setIndex(555478677);
            java.lang.Object _returnPropertiesProgramPropertyVal1Value = null;
            _returnPropertiesProgramPropertyVal1.setValue(_returnPropertiesProgramPropertyVal1Value);
            _returnPropertiesProgramProperty.add(_returnPropertiesProgramPropertyVal1);
            _returnProperties.getProgramProperty().addAll(_returnPropertiesProgramProperty);
            _return.setProperties(_returnProperties);
            _return.setName("Name-180676501");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.openhab.binding.atsadvanced.ISyncReply#programConfigurePanel(org.openhab.binding.atsadvanced.
     * ProgramConfigurePanel par )*
     */
    @Override
    public org.openhab.binding.atsadvanced.webservices.client.ProgramConfigurePanelResponse programConfigurePanel(
            ProgramConfigurePanel par) {
        LOG.info("Executing operation programConfigurePanel");
        System.out.println(par);
        try {
            org.openhab.binding.atsadvanced.webservices.client.ProgramConfigurePanelResponse _return = new org.openhab.binding.atsadvanced.webservices.client.ProgramConfigurePanelResponse();
            _return.setResult("Result-1764164808");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.openhab.binding.atsadvanced.ISyncReply#programConfigurePanel(org.openhab.binding.atsadvanced.
     * ProgramConfigurePanel par )*
     */
    @Override
    public org.openhab.binding.atsadvanced.webservices.client.ProgramConfigureGatewayResponse programConfigureGateway(
            ProgramConfigureGateway par) {
        LOG.info("Executing operation programConfigurePanel");
        System.out.println(par);
        try {
            org.openhab.binding.atsadvanced.webservices.client.ProgramConfigureGatewayResponse _return = new org.openhab.binding.atsadvanced.webservices.client.ProgramConfigureGatewayResponse();
            _return.setResult("Result-1764164808");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
