package org.openhab.binding.atsadvanced.webservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-23T16:43:57.547+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "ATSAdvanced.DTO", name = "ISyncReply")
@XmlSeeAlso({ObjectFactory.class, org.openhab.binding.atsadvanced.webservices.microsoft.ObjectFactory.class, org.openhab.binding.atsadvanced.webservices.datacontract.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ISyncReply {

    @WebResult(name = "Program.SendMessageResponse", targetNamespace = "ATSAdvanced.DTO", partName = "par")
    @WebMethod(operationName = "Program.SendMessage", action = "ATSAdvanced.DTO/Program.SendMessage")
    public ProgramSendMessageResponse programSendMessage(
        @WebParam(partName = "par", name = "Program.SendMessage", targetNamespace = "ATSAdvanced.DTO")
        ProgramSendMessage par
    );

    @WebResult(name = "Program.ConfigurePanelResponse", targetNamespace = "ATSAdvanced.DTO", partName = "par")
    @WebMethod(operationName = "Program.ConfigurePanel", action = "ATSAdvanced.DTO/Program.ConfigurePanel")
    public ProgramConfigurePanelResponse programConfigurePanel(
        @WebParam(partName = "par", name = "Program.ConfigurePanel", targetNamespace = "ATSAdvanced.DTO")
        ProgramConfigurePanel par
    );
    
    @WebResult(name = "Program.ConfigureGatewayResponse", targetNamespace = "ATSAdvanced.DTO", partName = "par")
    @WebMethod(operationName = "Program.ConfigureGateway", action = "ATSAdvanced.DTO/Program.ConfigureGateway")
    public ProgramConfigureGatewayResponse programConfigureGateway(
        @WebParam(partName = "par", name = "Program.ConfigureGateway", targetNamespace = "ATSAdvanced.DTO")
        ProgramConfigureGateway par
    );
}
