
package org.openhab.binding.atsadvanced.webservices.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-23T16:43:57.465+02:00
 * Generated source version: 3.0.0-milestone2
 *
 */
public final class ISyncReply_BasicHttpBindingISyncReply_Client {

    private static final QName SERVICE_NAME = new QName("ATSAdvanced.DTO", "SyncReply");

    private ISyncReply_BasicHttpBindingISyncReply_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SyncReply.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SyncReply ss = new SyncReply(wsdlURL, SERVICE_NAME);
        ISyncReply port = ss.getBasicHttpBindingISyncReply();

        {
            // System.out.println("Invoking programSendMessage...");
            // org.openhab.binding.atsadvanced.ProgramSendMessage _programSendMessage_par = new
            // org.openhab.binding.atsadvanced.ProgramSendMessage();
            // org.datacontract.schemas._2004._07.atsadvancedtest.ArrayOfProgramProperty
            // _programSendMessage_parProperties = new
            // org.datacontract.schemas._2004._07.atsadvancedtest.ArrayOfProgramProperty();
            // java.util.List<org.datacontract.schemas._2004._07.atsadvancedtest.ProgramProperty>
            // _programSendMessage_parPropertiesProgramProperty = new
            // java.util.ArrayList<org.datacontract.schemas._2004._07.atsadvancedtest.ProgramProperty>();
            // org.datacontract.schemas._2004._07.atsadvancedtest.ProgramProperty
            // _programSendMessage_parPropertiesProgramPropertyVal1 = new
            // org.datacontract.schemas._2004._07.atsadvancedtest.ProgramProperty();
            // _programSendMessage_parPropertiesProgramPropertyVal1.setId("Id1922158400");
            // _programSendMessage_parPropertiesProgramPropertyVal1.setIndex(1825987757);
            // java.lang.Object _programSendMessage_parPropertiesProgramPropertyVal1Value = null;
            // _programSendMessage_parPropertiesProgramPropertyVal1.setValue(_programSendMessage_parPropertiesProgramPropertyVal1Value);
            // _programSendMessage_parPropertiesProgramProperty.add(_programSendMessage_parPropertiesProgramPropertyVal1);
            // _programSendMessage_parProperties.getProgramProperty().addAll(_programSendMessage_parPropertiesProgramProperty);
            // _programSendMessage_par.setProperties(_programSendMessage_parProperties);
            // _programSendMessage_par.setName("Name-1331509845");
            // org.openhab.binding.atsadvanced.ProgramSendMessageResponse _programSendMessage__return =
            // port.programSendMessage(_programSendMessage_par);
            // System.out.println("programSendMessage.result=" + _programSendMessage__return);

        }
        {
            System.out.println("Invoking programConfigurePanel...");
            org.openhab.binding.atsadvanced.webservices.client.ProgramConfigurePanel _programConfigurePanel_par = new org.openhab.binding.atsadvanced.webservices.client.ProgramConfigurePanel();
            _programConfigurePanel_par.setHearbeat(682627670);
            _programConfigurePanel_par.setHostaddress("Hostaddress-1027605177");
            _programConfigurePanel_par.setPassword("Password-1698540543");
            _programConfigurePanel_par.setPort(-1354421157);
            _programConfigurePanel_par.setRetries(-1147687279);
            _programConfigurePanel_par.setTimeout(49664006);
            org.openhab.binding.atsadvanced.webservices.client.ProgramConfigurePanelResponse _programConfigurePanel__return = port
                    .programConfigurePanel(_programConfigurePanel_par);
            System.out.println("programConfigurePanel.result=" + _programConfigurePanel__return);

        }

        System.exit(0);
    }

}
